ProjectViews/Areas/User/Controllers/DetailController.cs
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectViews.Areas.User.Models;

namespace ProjectViews.Areas.User.Controllers
{
  [Area("User")]
  public class DetailController : Controller
  {
    private readonly HttpClient _httpClient;
    public DetailController()
    {
      _httpClient = new HttpClient();
      GetFeedback(nameShoe);
    }

    private string nameShoe;
    public async Task<IActionResult> DetailProduct(string name)
    {
      nameShoe = name;
      // Get all bill
      var apiUrls = "https://localhost:7109/api/ShoeDetails/get-all-shoeDetails";
      var responses = await _httpClient.GetAsync(apiUrls); // goi api lay data
      var apiDatas = await responses.Content.ReadAsStringAsync(); // doc data tra ve
      var shoeDetails = JsonConvert.DeserializeObject<List<ShoeDetails>>(apiDatas);
      // Get all Sale Event
      var apiURLss = "https://localhost:7109/api/Sales/Show-Sales";
      var responsess = await _httpClient.GetAsync(apiURLss);
      var apiDatass = await responsess.Content.ReadAsStringAsync();
      var sales = JsonConvert.DeserializeObject<List<Sales>>(apiDatass);
      //lay dữ liệu color từ bảng Color
      var apiUrlcolr = "https://localhost:7109/api/Color/get-all-colors";
      var responsecolr = await _httpClient.GetAsync(apiUrlcolr);
      var apiDatacolr = await responsecolr.Content.ReadAsStringAsync();
      var colors = JsonConvert.DeserializeObject<List<Colors>>(apiDatacolr);
      //lay dữ liệu size từ bảng Size
      var apiUrlsize = "https://localhost:7109/api/Size/get-all-size";
      var responsesize = await _httpClient.GetAsync(apiUrlsize);
      var apiDatasize = await responsesize.Content.ReadAsStringAsync();
      var sizes = JsonConvert.DeserializeObject<List<Sizes>>(apiDatasize);
      //lay du lieu tu bang Brand
      var apiUrlbrand = "https://localhost:7109/api/Brand/get-all-brands";
      var responsebrand = await _httpClient.PostAsync(apiUrlbrand, null);
      var apiDatabrand = await responsebrand.Content.ReadAsStringAsync();
      var brands = JsonConvert.DeserializeObject<List<Brands>>(apiDatabrand);
      //lay du lieu tu bang size_shoeDetail
      var apiUrlsize_shoeDetail = "https://localhost:7109/api/SIzes_ShoeDetails/get-all-size-shoe-details";
      var responsesize_shoeDetail = await _httpClient.GetAsync(apiUrlsize_shoeDetail);
      var apiDatasize_shoeDetail = await responsesize_shoeDetail.Content.ReadAsStringAsync();
      var size_shoeDetails = JsonConvert.DeserializeObject<List<Sizes_ShoeDetails>>(apiDatasize_shoeDetail);
      //lay du lieu tu bang color_shoeDetail
      var apiUrlcolor_shoeDetail = "https://localhost:7109/api/Color_ShoeDetails/get-all-color_shoeDetails";
      var apiDatacolor_shoeDetail = await _httpClient.GetAsync(apiUrlcolor_shoeDetail);
      var apiColorShoesDetails = await apiDatacolor_shoeDetail.Content.ReadAsStringAsync();
      var color_shoeDetails = JsonConvert.DeserializeObject<List<Color_ShoeDetails>>(apiColorShoesDetails);
      //lay du lieu tu bang image_shoeDetail
      string apiUrlImage = $"https://localhost:7109/api/Images/get-all-image";
      var responseImage = await _httpClient.GetAsync(apiUrlImage);
      string apiDataImage = await responseImage.Content.ReadAsStringAsync();
      var image_shoeDetails = JsonConvert.DeserializeObject<List<Images>>(apiDataImage);
      //lay du lieu category
      string apiUrl = $"https://localhost:7109/api/Categories/get-all-categories";
      var response = await _httpClient.GetAsync(apiUrl);
      string apidata = await response.Content.ReadAsStringAsync();
      var cat = JsonConvert.DeserializeObject<List<Categories>>(apidata);
      //lay du lieu tu bang supplier
      string apiUrl1 = "https://localhost:7109/api/Suppliers/get-all-supplier";
      var response1 = await _httpClient.GetAsync(apiUrl1);
      string apidata1 = await response1.Content.ReadAsStringAsync();
      var sp = JsonConvert.DeserializeObject<List<Supplier>>(apidata1);
      //lay du lieu tu bang brand
      string apiUrl2 = "https://localhost:7109/api/Brands/get-all-brands";
      var response2 = await _httpClient.GetAsync(apiUrl2);
      string apidata2 = await response2.Content.ReadAsStringAsync();
      var br = JsonConvert.DeserializeObject<List<Brands>>(apidata2);
      //lay du lieu tu bang descripion
      string apiUrlDescriptionsGetAll = $"https://localhost:7109/api/Descriptions/get-all";
      var responseDescriptionsGetAll = await _httpClient.GetAsync(apiUrlDescriptionsGetAll);
      string apiDataDescriptionsGetAll = await responseDescriptionsGetAll.Content.ReadAsStringAsync();
      var descriptions = JsonConvert.DeserializeObject<List<Descriptions>>(apiDataDescriptionsGetAll);
      //lay du lieu tu bang Feedback
      string apiUrlFeedbackGetAll = $"https://localhost:7109/api/Feedbacks/get-all-feedbacks";
      var responseFeedbackGetAll = await _httpClient.GetAsync(apiUrlFeedbackGetAll);
      string apiDataFeedbackGetAll = await responseFeedbackGetAll.Content.ReadAsStringAsync();
      var feedbacks = JsonConvert.DeserializeObject<List<Feedbacks>>(apiDataFeedbackGetAll);
      //Group shoe by name and add to list
      var lstShoes = new List<ShoeCategory>();
      var gourpList = shoeDetails.Where(p=>p.Name == name).ToList();
      //check group list count = 0
      foreach (var item in gourpList)
      {
        ShoeCategory shoe = new ShoeCategory();
        shoe.Id = item.Id;
        shoe.Name = item.Name;
        shoe.Supplier = sp.FirstOrDefault(p => p.Id == item.IdSupplier).Address;
        shoe.Brand = br.FirstOrDefault(p => p.Id == item.IdBrand).Name;
        shoe.Category = cat.FirstOrDefault(p => p.Id == item.IdCategory).CategoryName;
        shoe.CostPrice = item.CostPrice;
        shoe.SellPrice = item.SellPrice;
        shoe.Status = item.Status;
        shoe.AvailableQuantity = item.AvailableQuantity;
        shoe.DiscountValue = sales.FirstOrDefault(p => p.Id == item.IdSale).DiscountValue;
        shoe.ColorValue = "#" + colors.FirstOrDefault(p => p.Id == color_shoeDetails.FirstOrDefault(p => p.IdShoeDetail == item.Id).IdColor).ColorName;
        shoe.SizeValue = sizes.FirstOrDefault(p => p.Id == size_shoeDetails.FirstOrDefault(p => p.IdShoeDetails == item.Id).IdSize).SizeNumber;
        //check image null
        if (image_shoeDetails.FirstOrDefault(p => p.IdShoeDetail == item.Id) == null)
        {
          shoe.ImageSource="https://www.thermaxglobal.com/wp-content/uploads/2020/05/image-not-found.jpg";
        }
        else
        {
          shoe.ImageSource = image_shoeDetails.FirstOrDefault(p => p.IdShoeDetail == item.Id).ImageSource;
        }
        if (descriptions.FirstOrDefault(p => p.IdShoeDetail == item.Id) != null)
        {
          shoe.Decriptions1 = descriptions.FirstOrDefault(p => p.IdShoeDetail == item.Id).Note1;
          shoe.Decriptions2 = descriptions.FirstOrDefault(p => p.IdShoeDetail == item.Id).Note2;
          shoe.Decriptions3 = descriptions.FirstOrDefault(p => p.IdShoeDetail == item.Id).Note3;
        }
        else
        {
          shoe.Decriptions1 = "No description";
          shoe.Decriptions2 = "No description";
          shoe.Decriptions3 = "No description";
        }
        //check feedback null
        if (feedbacks.FirstOrDefault(p => p.IdShoeDetail == item.Id) == null)
        {
          shoe.RateStar = new List<int>();
          shoe.RateStar.Add(0);
          shoe.LstFeedbacks = new List<string>();
          shoe.LstFeedbacks.Add("No feedback");
        }
        else
        {
          shoe.LstFeedbacks = feedbacks.Where(p => p.IdShoeDetail == item.Id).Select(p => p.Note).ToList();
          shoe.RateStar = feedbacks.Where(p => p.IdShoeDetail == item.Id).Select(p => p.RatingStar).ToList();
        }
        lstShoes.Add(shoe);
      }
      return View(lstShoes);
    }

    public ActionResult GetPdf()
    {
      string filePath = "~/UserAsssets/pdf/How-to-choose-a-size.pdf";
      return File(filePath, "application/pdf");
    }

    public async void GetFeedback(string name)
    {
      //get feedback from api
      string apiURL = $"https://localhost:7109/api/Feedbacks/get-all-feedbacks";
      var response = await _httpClient.GetAsync(apiURL);
      var apiData = await response.Content.ReadAsStringAsync();
      var feedbacks = JsonConvert.DeserializeObject<List<Feedbacks>>(apiData);
      //get shoes from api
      var apiUrls = "https://localhost:7109/api/ShoeDetails/get-all-shoeDetails";
      var responses = await _httpClient.GetAsync(apiUrls); // goi api lay data
      var apiDatas = await responses.Content.ReadAsStringAsync(); // doc data tra ve
      var shoeDetails = JsonConvert.DeserializeObject<List<ShoeDetails>>(apiDatas);
      //get list feedback by name shoe
      List<Feedbacks> lstFeedbacks = new List<Feedbacks>();
      foreach (var item in shoeDetails)
      {
        if (item.Name == name)
        {
          lstFeedbacks = feedbacks.Where(p => p.IdShoeDetail == item.Id).ToList();
        }
      }
      ViewBag.Feedbacks = lstFeedbacks;
    }
    public async void GetAvailableQuantity(Guid idColor, Guid idSize)
    {
      //get shoes from api
      var apiUrls = "https://localhost:7109/api/ShoeDetails/get-all-shoeDetails";
      var responses = await _httpClient.GetAsync(apiUrls); // goi api lay data
      var apiDatas = await responses.Content.ReadAsStringAsync(); // doc data tra ve
      var shoeDetails = JsonConvert.DeserializeObject<List<ShoeDetails>>(apiDatas);
      //lay du lieu tu bang size_shoeDetail
      var apiUrlsize_shoeDetail = "https://localhost:7109/api/SIzes_ShoeDetails/get-all-size-shoe-details";
      var responsesize_shoeDetail = await _httpClient.GetAsync(apiUrlsize_shoeDetail);
      var apiDatasize_shoeDetail = await responsesize_shoeDetail.Content.ReadAsStringAsync();
      var size_shoeDetails = JsonConvert.DeserializeObject<List<Sizes_ShoeDetails>>(apiDatasize_shoeDetail);

ProjectViews/Controllers/ImagesController.cs
using System.Reflection;
using System.Text;
using Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ProjectViews.Controllers
{
  public class ImagesController : Controller
  {
    private readonly HttpClient _httpClient;

    public ImagesController()
    {
      _httpClient = new HttpClient();
    }

    // GET: ImageController
    public async Task<IActionResult> Show()
    {
      string apiUrl = $"https://localhost:7109/api/Images/get-all-image";
      var response = await _httpClient.GetAsync(apiUrl);
      string apiData = await response.Content.ReadAsStringAsync();
      var images = JsonConvert.DeserializeObject<IEnumerable<Images>>(apiData);
      return View(images);
    }
    //create

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Images images, IFormFile file)
    {
      if (file != null && file.Length > 0)
      {
        var fileName = Path.GetFileName(file.FileName);
        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UserAsssets/images", fileName);
        using (var fileStream = new FileStream(filePath, FileMode.Create))
        {
          await file.CopyToAsync(fileStream);
        }
        images.ImageSource = fileName;
      }
      string url =
          $"https://localhost:7109/api/Images/create-image?imageUrl={images.ImageSource}&idShoesDetails={images.IdShoeDetail}";
      var json = JsonConvert.SerializeObject(images);
      var data = new StringContent(json, Encoding.UTF8, "application/json");
      var response = await _httpClient.PostAsync(url, data);
      if (response.IsSuccessStatusCode)
      {
        return RedirectToAction("Show");
      }
      return RedirectToAction("Show");

    }

    //details
    public async Task<IActionResult> Detail(Guid id)
    {
      var response = await _httpClient.GetAsync($"https://localhost:7109/api/Images/get-image-by-id?id={id}");
      var result = await response.Content.ReadAsStringAsync();
      var image = JsonConvert.DeserializeObject<Images>(result);
      if (response.IsSuccessStatusCode)
      {
        return View(image);
      }
      return NotFound();
    }

    //update
    [HttpGet]
    public async Task<IActionResult> Update(Guid id)
    {
      //get supplier by id
      var response = await _httpClient.GetAsync($"https://localhost:7109/api/Images/get-image-by-id?id={id}");
      var result = await response.Content.ReadAsStringAsync();
      var image = JsonConvert.DeserializeObject<Images>(result);
      if (response.IsSuccessStatusCode)
      {
        return View(image);
      }

      return NotFound();
    }

    //delete
    [HttpPost]
    public async Task<IActionResult> Update(Images images, IFormFile file)
    {
      if (file != null && file.Length > 0)
      {
        var fileName = Path.GetFileName(file.FileName);
        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UserAsssets/images", fileName);
        using (var fileStream = new FileStream(filePath, FileMode.Create))
        {
          await file.CopyToAsync(fileStream);
        }

        images.ImageSource = fileName;
      }

      string url =
          $"https://localhost:7109/api/Images/update-image-by-id?id={images.Id}&imageUrl={images.ImageSource}&idShoesDetails={images.IdShoeDetail}";
      var json = JsonConvert.SerializeObject(images);
      var data = new StringContent(json, Encoding.UTF8, "application/json");
      var response = await _httpClient.PutAsync(url, data);
      if (response.IsSuccessStatusCode)
      {
        return RedirectToAction("Show");
      }
      return RedirectToAction("Show");

    }
    //delete
    public async Task<IActionResult> Delete(Guid Id)
    {
      string url = $"https://localhost:7109/api/Images/delete-image-by-id?id={Id}";
      var response = await _httpClient.DeleteAsync(url);
      if (response.IsSuccessStatusCode)
      {
        return RedirectToAction("Show");
      }
      return BadRequest();
    }
  }
}

ProjectViews/Views/ShoesDetails/Details.cshtml
@using Data.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Newtonsoft.Json
@model Data.Models.ShoeDetails

@{
    ViewData["Title"] = "Details";
    HttpClient _httpClient = new HttpClient();
    List<string> imageExtensions = new List<string>()
    {
        ".png", ".jpg", ".jpeg", ".gif", ".tiff", ".pdf"
    };
    string apiUrls = $"https://localhost:7109/api/ShoeDetails/get-all-shoeDetails";
    var responses = await _httpClient.GetAsync(apiUrls); // goi api lay data
    string apiDatas = await responses.Content.ReadAsStringAsync(); // doc data tra ve
    var shoeDetails = JsonConvert.DeserializeObject<List<ShoeDetails>>(apiDatas);
    //lay dữ liệu color từ bảng Color
    string apiUrlcolr = $"https://localhost:7109/api/Color/get-all-colors";
    var responsecolr = await _httpClient.GetAsync(apiUrlcolr);
    string apiDatacolr = await responsecolr.Content.ReadAsStringAsync();
    var colors = JsonConvert.DeserializeObject<List<Colors>>(apiDatacolr);
    //lay dữ liệu size từ bảng Size
    string apiUrlsize = $"https://localhost:7109/api/Size/get-all-size";
    var responsesize = await _httpClient.GetAsync(apiUrlsize);
    string apiDatasize = await responsesize.Content.ReadAsStringAsync();
    var sizes = JsonConvert.DeserializeObject<List<Sizes>>(apiDatasize);
    //lay du lieu tu bang colorshoe
    string apiUrlsize_shoeDetail = $"https://localhost:7109/api/SIzes_ShoeDetails/get-all-size-shoe-details";
    var responsesize_shoeDetail = await _httpClient.GetAsync(apiUrlsize_shoeDetail);
    string apiDatasize_shoeDetail = await responsesize_shoeDetail.Content.ReadAsStringAsync();
    var size_shoeDetails = JsonConvert.DeserializeObject<List<Sizes_ShoeDetails>>(apiDatasize_shoeDetail);
    //lay du lieu tu bang color_shoeDetail
    string apiUrlcolor_shoeDetail = $"https://localhost:7109/api/Color_ShoeDetails/get-all-color_shoeDetails";
    var apiDatacolor_shoeDetail = await _httpClient.GetAsync(apiUrlcolor_shoeDetail);
    string apiColorShoesDetails = await apiDatacolor_shoeDetail.Content.ReadAsStringAsync();
    var color_shoeDetails = JsonConvert.DeserializeObject<List<Color_ShoeDetails>>(apiColorShoesDetails);
}

<h1>Details</h1>

<div>
    <h4>ShoeDetails</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            Supplier
        </dt>
        <dd class="col-sm-10">
            @{
                string apiUrl1 = "https://localhost:7109/api/Suppliers/get-all-supplier";
                var response1 = await _httpClient.GetAsync(apiUrl1);
                string apidata1 = await response1.Content.ReadAsStringAsync();
                var sp = JsonConvert.DeserializeObject<List<Supplier>>(apidata1);
                var supplier = sp.Where(x => x.Id == Model.IdSupplier).FirstOrDefault();
            }
            @Html.DisplayFor(model => supplier.Address)
        </dd>
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @{
                string apiUrl = $"https://localhost:7109/api/Categories/get-all-categories";
                var response = await _httpClient.GetAsync(apiUrl);
                string apidata = await response.Content.ReadAsStringAsync();
                var cat = JsonConvert.DeserializeObject<List<Categories>>(apidata);
                var category = cat.Where(x => x.Id == Model.IdCategory).FirstOrDefault();
            }
            @Html.DisplayFor(model => category.CategoryName)
        </dd>
        <dt class="col-sm-2">
            Brands
        </dt>
        <dd class="col-sm-10">
            @{
                string apiUrl2 = $"https://localhost:7109/api/Brands/get-all-brands";
                var response2 = await _httpClient.GetAsync(apiUrl2);
                string apidata2 = await response2.Content.ReadAsStringAsync();
                var br = JsonConvert.DeserializeObject<List<Brands>>(apidata2);
                //load du lieu vao dropdownlist
                var brand = br.Where(x => x.Id == Model.IdBrand).FirstOrDefault();
            }
            @Html.DisplayFor(model => brand.Name)
        </dd>
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Cost Price
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CostPrice)
        </dd>
        <dt class="col-sm-2">
            Sell Price
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SellPrice)
        </dd>
        <dt class="col-sm-2">
            Available Quantity
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AvailableQuantity)
        </dd>
        <dt class="col-sm-2">
            Status
        </dt>
        <dd class="col-sm-10">
            @{
                if (Model.Status == 1)
                {
                    <span class="text-success">Active</span>
                }
                else
                {
                    <span class="text-danger">Inactive</span>
                }
            }
        </dd>
        <dt class="col-sm-2">
            Sale Name
        </dt>
        <dd class="col-sm-10">
            @{
                string apiUrl3 = $"https://localhost:7109/api/Sales/Show-Sales";
                var response3 = await _httpClient.GetAsync(apiUrl3);
                string apidata3 = await response3.Content.ReadAsStringAsync();
                var sl = JsonConvert.DeserializeObject<List<Sales>>(apidata3);
                var sale = sl.Where(x => x.Id == Model.IdSale).FirstOrDefault();
            }
            @Html.DisplayFor(model => sale.SaleName)
        </dd>
        <dt class="col-md-2">
            Size
        </dt>
        <dd class="col-md-10">
            @{
                var size = sizes.FirstOrDefault(p => p.Id == size_shoeDetails.FirstOrDefault(p => p.IdShoeDetails == Model.Id).IdSize).SizeNumber;
            }
            @size
        </dd>
        <dt class="col-md-2">
            Color
        </dt>
        <dd class="col-md-10">
            @{
                var idColor = color_shoeDetails.FirstOrDefault(p => p.IdShoeDetail == Model.Id).IdColor;
                var colorName = colors.FirstOrDefault(p => p.Id == idColor).ColorName;
            }
            <span class="dot" style="background-color: #@colorName"></span>
        </dd>
        <dt class="col-md-2">
            Image
        </dt>
        <dd class="col-md-10">
            @{
                string apiUrlImage = $"https://localhost:7109/api/Images/get-all-image";
                var respo = await _httpClient.GetAsync(apiUrlImage);
                var apiimage = await respo.Content.ReadAsStringAsync();
                var images = JsonConvert.DeserializeObject<List<Images>>(apiimage);
                var imageShoe = images.FirstOrDefault(p => p.IdShoeDetail == Model.Id);
            }
            @if (imageShoe == null)
            {
                <p>No image Create Now ? <a asp-action="Create" asp-controller="Images">Create Now?</a></p>
            }
            else
            {
                <img src="@imageShoe.ImageSource" height="100px">
            }
        </dd>
        <dt class="col-md-2">
            Decsription
        </dt>
        <dd class="col-md-10">
            @{
                string url = $"https://localhost:7109/api/Descriptions/get-all";
                var reo = _httpClient.GetAsync(url);
                var apiDataDis = await reo.Result.Content.ReadAsStringAsync();
                var des = JsonConvert.DeserializeObject<List<Descriptions>>(apiDataDis);
                var description = des.FirstOrDefault(p => p.IdShoeDetail == Model.Id);
            }
            @if (description == null)
            {
                <p>No description Create Now ? <a asp-action="Create" asp-controller="Description">Create Now?</a></p>
            }
            else
            {
                @description.Note1
                <br>
                @description.Note2
                <br>
                @description.Note3
            }
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Show">Back to List</a>
</div>
<style>
    .dot {
        height: 25px;
        width: 25px;
        border-radius: 50%;
        display: inline-block;
    }
</style>